apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: shepard-frontend
  namespace: shepard
spec:
  gateways:
    - shepard/shepard-gateway
  hosts:
    - '*'
  http:
    - name: "shepard-frontend-route"
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: frontend.shepard.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak-dex
  namespace: keycloak
spec:
  gateways:
    - shepard/shepard-gateway
  hosts:
    - '*'
  http:
    - name: "shepard-dex-auth-route"
      match:
        - uri:
            prefix: /dex/
      route:
        - destination:
            host: dex.auth.svc.cluster.local
            port:
              number: 5556