apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
  namespace: keycloak
spec:
  gateways:
    - keycloak/keycloak-gateway
  hosts:
    - '*'
  http:
    - name: "keycloak-route"
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: keycloak.keycloak.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak-dex
  namespace: keycloak
spec:
  gateways:
    - keycloak/keycloak-gateway
  hosts:
    - '*'
  http:
    - name: "keycloak-dex-auth-route"
      match:
        - uri:
            prefix: /dex/
      route:
        - destination:
            host: dex.auth.svc.cluster.local
            port:
              number: 5556