---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shepard-ingress-cert
  namespace: istio-system
spec:
  secretName: shepard-ingress-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "$SHEPARD_DNS_NAME"